development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] || 'uts_rag_development' %>
  username: <%= ENV['DB_USER'] || ENV['USER'] %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME_TEST'] || 'uts_rag_test' %>
  username: <%= ENV['DB_USER'] || ENV['USER'] %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] || 'uts_rag_production' %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>

